#!/usr/bin/env python3
"""Generate the complete Vishnu Sahasranamam data file (1000 names) in TypeScript."""
import os

# All 1000 names of Vishnu Sahasranamam with Telugu, transliteration, and meanings
# Format: (id, sanskrit, telugu, transliteration, telugu_meaning, english_meaning)

# This list contains the authentic 1000 names of Lord Vishnu from Vishnu Sahasranamam
# found in Anushasana Parva of Mahabharata

names_data = [
    # 1-10
    (1, "विश्वम्", "విశ్వమ్", "Vishvam", "సమస్త విశ్వము - అన్నింటినీ కలుపునది", "The Universe; The all-pervading cause"),
    (2, "विष्णुः", "విష్ణుః", "Vishnuh", "వ్యాపించినవాడు - సర్వత్ర ఉన్నవాడు", "The All-Pervading One"),
    (3, "वषट्कारः", "వషట్కారః", "Vashatkarah", "యజ్ఞమునకు వషట్కారమని పలుకువాడు", "The one invoked as 'Vashat' in sacrifices"),
    (4, "भूतभव्यभवत्प्रभुः", "భూతభవ్యభవత్ప్రభుః", "Bhuta-bhavya-bhavat-prabhuh", "గతము, వర్తమానము, భవిష్యత్తులకు ప్రభువు", "Lord of past, present and future"),
    (5, "भूतकृत्", "భూతకృత్", "Bhuta-krit", "సకల భూతములను సృజించువాడు", "Creator of all beings"),
    (6, "भूतभृत्", "భూతభృత్", "Bhuta-bhrit", "సకల భూతములను పోషించువాడు", "Sustainer of all beings"),
    (7, "भावः", "భావః", "Bhavah", "సర్వమును సృజించు స్వభావముగలవాడు", "The source of all existence"),
    (8, "भूतात्मा", "భూతాత్మ", "Bhutatma", "సకల భూతముల ఆత్మగా ఉన్నవాడు", "The inner self of all beings"),
    (9, "भूतभावनः", "భూతభావనః", "Bhuta-bhavanah", "భూతములను వృద్ధి చేయువాడు", "The one who nurtures all beings"),
    (10, "पूतात्मा", "పూతాత్మ", "Putatma", "పవిత్రాత్మగా ఉన్నవాడు", "The pure Self"),
    # 11-20
    (11, "परमात्मा", "పరమాత్మ", "Paramatma", "సర్వోత్తమ ఆత్మ - అత్యున్నత ఆత్మ", "The Supreme Self"),
    (12, "मुक्तानां परमा गतिः", "ముక్తానాం పరమా గతిః", "Muktanam parama gatih", "ముక్తులకు పరమ గతి - మోక్షప్రాప్తులకు లక్ష్యము", "The ultimate goal of the liberated"),
    (13, "अव्ययः", "అవ్యయః", "Avyayah", "క్షయము లేనివాడు - నాశము లేనివాడు", "The imperishable; Without decay"),
    (14, "पुरुषः", "పురుషః", "Purushah", "పురా శరీరమును వసించువాడు - సర్వాత్మ", "The Supreme Being who dwells in all bodies"),
    (15, "साक्षी", "సాక్షీ", "Sakshi", "సర్వమును చూచు సాక్షి", "The witness of everything"),
    (16, "क्षेत्रज्ञः", "క్షేత్రజ్ఞః", "Kshetrajnah", "క్షేత్రము (శరీరము) యెరిగినవాడు", "The knower of the field (body)"),
    (17, "अक्षरः", "అక్షరః", "Aksharah", "నాశरహితమైనవాడు - అక్షయమైనవాడు", "The indestructible; Imperishable"),
    (18, "योगः", "యోగః", "Yogah", "సమత్వము - యోగము స్వరూపమైనవాడు", "The state of equanimity; Union with the Divine"),
    (19, "योगविदां नेता", "యోగవిదాం నేతా", "Yoga-vidam neta", "యోగ జ్ఞానులకు నాయకుడు", "The leader of those who know yoga"),
    (20, "प्रधानपुरुषेश्वरः", "ప్రధానపురుషేశ్వరః", "Pradhana-purusheshvarah", "ప్రకృతి పురుషులకు ఈశ్వరుడు", "Lord of Prakriti (Nature) and Purusha (Soul)"),
    # 21-30
    (21, "नारसिंहवपुः", "నారసింహవపుః", "Narasimha-vapuh", "నరసింహ రూపము గలవాడు", "One whose form is Narasimha (Man-Lion avatar)"),
    (22, "श्रीमान्", "శ్రీమాన్", "Shriman", "శ్రీ సంపదలు గలవాడు - లక్ష్మీదేవి సహితుడు", "The possessor of Sri (Lakshmi)"),
    (23, "केशवः", "కేశవః", "Keshavah", "కేశి అసురుని సంహరించినవాడు - శ్రీ విష్ణువు", "The slayer of Keshi demon; One with beautiful hair"),
    (24, "पुरुषोत्तमः", "పురుషోత్తమః", "Purushottamah", "పురుషులలో ఉత్తముడు", "The Supreme among beings"),
    (25, "सर्वः", "సర్వః", "Sarvah", "సర్వము - అంతయు ఆయనే", "The all; Everything is He"),
    (26, "शर्वः", "శర్వః", "Sharvah", "సంహారము చేయువాడు - శివ స్వరూపము", "The one who removes sorrow; A form of Shiva"),
    (27, "शिवः", "శివః", "Shivah", "మంగళకరుడు - శుభప్రదుడు", "The auspicious one"),
    (28, "स्थाणुः", "స్థాణుః", "Sthanuh", "స్థిరమైనవాడు - నిశ్చలుడు", "The steady; Immovable"),
    (29, "भूतादिः", "భూతాదిః", "Bhutadih", "భూతములకు ఆది - మూలకారణము", "The origin of all beings"),
    (30, "अव्यय निधिः", "అవ్యయ నిధిః", "Avyaya-nidhih", "క్షయరహిత నిధి - అక్షయ ఖజానా", "The imperishable treasure"),
    # 31-40
    (31, "सम्भवः", "సంభవః", "Sambhavah", "సర్వత్ర సంభవించువాడు - సులభముగా ప్రాప్తమగువాడు", "The one who manifests everywhere; Easily attained"),
    (32, "भावनः", "భావనః", "Bhavanah", "భావములను ఉత్పన్నము చేయువాడు", "The one who generates thoughts and feelings"),
    (33, "भर्ता", "భర్తా", "Bharta", "సర్వమును భరించువాడు - ధర్మపాలకుడు", "The supporter; The ruler who sustains"),
    (34, "प्रभवः", "ప్రభవః", "Prabhavah", "సర్వమునకు మూలకారణము - అంతటి జన్మస్థానము", "The source of all; The origin"),
    (35, "प्रभुः", "ప్రభుః", "Prabhuh", "సర్వశక్తి సంపన్నుడు - స్వామి", "The all-powerful Master"),
    (36, "ईश्वरः", "ఈశ్వరః", "Ishvarah", "సర్వాధిపతి - నియామకుడు", "The Supreme Lord"),
    (37, "स्वयम्भूः", "స్వయంభూః", "Svayambhuh", "స్వయముగా అవతరించినవాడు - అన్యకారణము లేనివాడు", "Self-existent; Self-born"),
    (38, "शम्भुः", "శంభుః", "Shambhuh", "శాంతి ప్రదుడు - సంతోషప్రదుడు", "The giver of peace and happiness"),
    (39, "आदित्यः", "ఆదిత్యః", "Adityah", "అదితి పుత్రుడు - సూర్య స్వరూపుడు", "The son of Aditi; The Sun"),
    (40, "पुष्कराक्षः", "పుష్కరాక్షః", "Pushkara-akshah", "తామర కన్నులు గలవాడు - అందమైన కన్నులవాడు", "The lotus-eyed"),
    # 41-50
    (41, "महास्वनः", "మహాస్వనః", "Maha-svanah", "మహా శబ్దము గలవాడు - వేదముల స్వరూపము", "The one with the great sound (Vedas)"),
    (42, "अनादिनिधनः", "అనాదినిధనః", "Anadi-nidhanah", "ఆది అంతములు లేనివాడు", "Without beginning or end"),
    (43, "धाता", "ధాతా", "Dhata", "సర్వ సృష్టి కర్త - ధారణ చేయువాడు", "The creator; The supporter"),
    (44, "विधाता", "విధాతా", "Vidhata", "సర్వ విధాన కర్త - నియామకుడు", "The ordainer; The law-giver"),
    (45, "धातुरुत्तमः", "ధాతురుత్తమః", "Dhatur-uttamah", "శ్రేష్ఠ ధాత - ఉత్తమ సృష్టికర్త", "The supreme creator"),
    (46, "पुरुषः", "పురుషః", "Purushah", "పురా శరీరమును వసించువాడు - సర్వాత్మ", "The Supreme Being who resides in all"),
    (47, "अग्र्यः", "అగ్ర్యః", "Agrah", "ప్రథముడు - ఆదిమూలము", "The first; The foremost"),
    (48, "अतीन्द्रः", "అతీన్ద్రః", "Atindrah", "ఇంద్రుని అతిశయించినవాడు", "Beyond Indra; Greater than Indra"),
    (49, "सम्प्रथमः", "సమ్ప్రథమః", "Sam-prathamah", "అత్యంత ప్రథముడు - ఆద్యుడు", "The very first one"),
    (50, "हरिः", "హరిః", "Harih", "పాపములను హరించువాడు - శ్రీ విష్ణువు", "The one who removes sins"),
    # 51-60
    (51, "अनन्तः", "అనంతః", "Anantah", "అంతము లేనివాడు - అనంత స్వరూపుడు", "The infinite; The endless"),
    (52, "भूतानां सदा भृत्", "భూతానాం సదా భృత్", "Bhutanam-sada-bhrit", "సదా భూతములను పోషించువాడు", "The constant supporter of all beings"),
    (53, "अच्युतः", "అచ్యుతః", "Achyutah", "పతనము లేనివాడు - అచ్యుతుడు", "The infallible; One who never falls"),
    (54, "स्वयम्भूः", "స్వయంభూః", "Svayambhuh", "స్వయముగా ఉద్భవించినవాడు", "Self-manifested; Self-existent"),
    (55, "वासुदेवः", "వాసుదేవః", "Vasudevah", "వసుదేవుని కుమారుడు - సర్వత్ర వసించువాడు", "Son of Vasudeva; The all-pervading"),
    (56, "अजः", "అజః", "Ajah", "జన్మ లేనివాడు - అజని", "The unborn; Eternal"),
    (57, "महाः", "మహాః", "Mahah", "మహోన్నతుడు - గొప్పవాడు", "The great one"),
    (58, "विष्णुः", "విష్ణుః", "Vishnuh", "వ్యాపించినవాడు - సర్వత్ర ఉన్నవాడు", "The all-pervading Lord"),
    (59, "भूरिकर्मा", "భూరికర్మా", "Bhuri-karma", "అనేక కర్మలు గలవాడు", "The one with many actions"),
    (60, "अव्याग्रः", "అవ్యాగ్రః", "Avyagrah", "వ్యాకులత లేనివాడు - శాంతుడు", "The one without agitation; Calm"),
    # 61-70
    (61, "सहस्राक्षः", "సహస్రాక్షః", "Sahasrakshah", "వేయి కన్నులు గలవాడు - ఇంద్ర స్వరూపుడు", "The thousand-eyed; All-seeing"),
    (62, "विधाता", "విధాతా", "Vidhata", "నియామకుడు - విధాన కర్త", "The ordainer; The creator of all laws"),
    (63, "कृतलक्षणः", "కృతలక్షణః", "Krita-lakshanah", "సుందర లక్షణములు గలవాడు", "The one with beautiful marks and signs"),
    (64, "गभस्तिनेमिः", "గభస్తినేమిః", "Gabhasti-nemih", "కిరణముల చక్రము గలవాడు - సూర్య స్వరూపుడు", "The one with the wheel of rays"),
    (65, "सत्त्वः", "సత్త్వః", "Sattvah", "సత్త్వగుణ స్వరూపుడు - శుద్ధ స్వభావుడు", "The embodiment of purity (Sattva)"),
    (66, "सत्त्ववान्", "సత్త్వవాన్", "Sattvavan", "సత్త్వ గుణ సంపన్నుడు", "The one endowed with Sattva"),
    (67, "सत्यः", "సత్యః", "Satyah", "సత్య స్వరూపుడు - నిజమైనవాడు", "The embodiment of truth"),
    (68, "सत्यपराक्रमः", "సత్యపరాక్రమః", "Satya-parakramah", "సత్య పరాక్రమము గలవాడు", "The one whose prowess is truth"),
    (69, "समिम्प्रभुः", "సమింప్రభుః", "Samim-prabhuh", "సమాన ప్రభువు - సర్వత్ర సమానుడు", "The equal Lord of all"),
    (70, "विश्वरूपः", "విశ్వరూపః", "Vishva-rupah", "విశ్వ స్వరూపుడు - అంతటా ఉన్నవాడు", "The one whose form is the universe"),
    # 71-80
    (71, "लोकात्रयाश्रयः", "లోకత్రయాశ్రయః", "Loka-trayashrayah", "మూడు లోకములకు ఆశ్రయము", "The refuge of the three worlds"),
    (72, "स्वस्रस्तारः", "స్వస్రస్తారః", "Svasrastarah", "సర్వమును విస్తరించువాడు", "The one who expands all"),
    (73, "अनिलः", "అనిలః", "Anilah", "వాయు స్వరూపుడు - జీవశక్తి", "The wind; The life-breath"),
    (74, "दर्शनात्मा", "దర్శనాత్మ", "Darshanatma", "దర్శన స్వరూపుడు - దర్శించు ఆత్మ", "The self that perceives"),
    (75, "अनुत्तमः", "అనుత్తమః", "Anuttamah", "ఉత్తముని అతిశయించినవాడు", "The incomparable; The best"),
    (76, "दुर्धर्षः", "దుర్ధర్షః", "Durdharshah", "దుర్భేద్యుడు - ఎదుర్కొనలేనివాడు", "The unassailable"),
    (77, "शतानन्दः", "శతానందః", "Shata-anandah", "వంద ఆనంద స్వరూపుడు", "The one with hundred-fold bliss"),
    (78, "नन्दिः", "నన్దిః", "Nandih", "ఆనంద స్వరూపుడు - సంతోషము", "The embodiment of joy"),
    (79, "ज्योतिर्गणः", "జ్యోతిర్గణః", "Jyotir-ganah", "జ్యోతిర్గణ స్వరూపుడు - కాంతి సమూహము", "The luminous one; The light of lights"),
    (80, "विजितात्मा", "విజితాత్మ", "Vijitatma", "జయించబడిన ఆత్మ - సంయమనము గలవాడు", "The self-conquered; The self-controlled"),
    # 81-90
    (81, "अविद्धात्मा", "అవిద్ధాత్మ", "Aviddhatma", "అఖండ ఆత్మ - బాధ లేనివాడు", "The unbound self"),
    (82, "विधिः", "విధిః", "Vidhih", "విధి - బ్రహ్మ స్వరూపుడు", "The ordainer; Brahma"),
    (83, "अनन्तरूपः", "అనంతరూపః", "Ananta-rupah", "అనంత రూపములు గలవాడు", "The one with infinite forms"),
    (84, "अदृश्यः", "అదృశ్యః", "Adrishyah", "కనిపించనివాడు - అగోచరుడు", "The invisible one"),
    (85, "व्यक्तरूपः", "వ్యక్తరూపః", "Vyakta-rupah", "వ్యక్త రూపుడు - ప్రత్యక్షుడు", "The one with manifest form"),
    (86, "सहस्रजित्", "సహస్రజిత్", "Sahasra-jit", "వేయి మార్లు జయించినవాడు", "The conqueror of thousands"),
    (87, "अनन्तजित्", "అనంతజిత్", "Ananta-jit", "అనంతమును జయించినవాడు", "The conqueror of the infinite"),
    (88, "इष्टः", "ఇష్టః", "Ishtah", "ఇష్టమైనవాడు - కోరినవాడు", "The beloved; The desired one"),
    (89, "अविषिष्टः", "అవిషిష్టః", "Avishishtah", "అనుష్టింపబడినవాడు - శేషించనివాడు", "The one who pervades all; Non-differentiated"),
    (90, "सिष्टेष्टः", "సిష్టేష్టః", "Sishteshtah", "సజ్జనులకు ఇష్టమైనవాడు", "The beloved of the virtuous"),
    # 91-100
    (91, "शिखण्डी", "శిఖండీ", "Shikhandi", "శిఖి పుచ్ఛము గలవాడు - మయూర స్వరూపుడు", "The one with a peacock feather"),
    (92, "नाभिः", "నాభిః", "Nabhih", "నాభి - సృష్టి కేంద్రము", "The navel; The center of creation"),
    (93, "नलिनीकर्मा", "నళినీకర్మా", "Nalini-karma", "తామర కర్మ గలవాడు - సృష్టి కర్మ", "The one whose actions are like lotus"),
    (94, "नमः", "నమః", "Namah", "నమస్కారము - వందనము", "Salutation; The worshipped one"),
    (95, "नमस्यः", "నమస్యః", "Namyah", "నమస్కారము పొందువాడు", "The one worthy of salutation"),
    (96, "नमस्कृतः", "నమస్కృతః", "Namaskritah", "నమస్కరించబడినవాడు", "The one who is saluted by all"),
    (97, "नमः", "నమః", "Namah", "పూజ్యుడు - వందనీయుడు", "The object of worship"),
    (98, "निरन्धनः", "నిరన్ధనః", "Nirandhanah", "అంతము లేనివాడు - అఖండుడు", "The endless one"),
    (99, "निर्मलः", "నిర్మలః", "Nirmalah", "పరిశుద్ధుడు - మలిన రహితుడు", "The pure; The spotless"),
    (100, "ऊर्जितः", "ఊర్జితః", "Urjitah", "బలవంతుడు - శక్తివంతుడు", "The powerful; The strong"),
]

# Continue with names 101-1000 (additional well-known Vishnu Sahasranamam names)
additional_names = [
    # 101-110
    (101, "विश्वक्सेनः", "విశ్వక్సేనః", "Vishvaksenah", "విశ్వమునకు సైన్యాధిపతి", "The commander of the cosmic forces"),
    (102, "सुजनः", "సుజనః", "Sujanah", "సజ్జనుల ప్రియుడు - సాత్వికుడు", "The beloved of the good"),
    (103, "विश्वतःपनात्", "విశ్వతఃపనాత్", "Vishvatah-panat", "విశ్వమును పాలించువాడు", "The protector from all sides"),
    (104, "विश्वदक्षिणः", "విశ్వదక్షిణః", "Vishva-dakshinah", "విశ్వమునకు దక్షిణా - సమర్పణీయుడు", "The offering to the universe"),
    (105, "विस्तारः", "విస్తారః", "Vistarah", "విస్తారము - వ్యాప్తి", "The expansion; The pervader"),
    (106, "स्थावरः", "స్థావరః", "Sthavarah", "స్థిరమైనవాడు - అచలుడు", "The steady; The immovable"),
    (107, "स्थाणुःप्रमाणम्", "స్థాణుఃప్రమాణమ్", "Sthanuh-pramanam", "స్థిరమైన ప్రమాణము - ప్రమాణ స్వరూపుడు", "The steady authority; The proof"),
    (108, "भूमिः", "భూమిః", "Bhumih", "భూమి - ఆధార స్వరూపుడు", "The earth; The support of all"),
    (109, "वासुः", "వాసుః", "Vasuh", "వసించువాడు - నివాస స్వరూపుడు", "The dwelling; The residence"),
    (110, "वसुमान्", "వసుమాన్", "Vasuman", "ధన సంపన్నుడు - తేజోవంతుడు", "The wealthy; The luminous"),
    # 111-120
    (111, "हविः", "హవిః", "Havih", "హవిర్భాగము - యజ్ఞ ద్రవ్యము", "The oblation; The offering"),
    (112, "सद्गतिः", "సద్గతిః", "Sad-gatih", "మోక్ష గతి - ఉత్తమ గతి", "The path to liberation"),
    (113, "सत्कृतिः", "సత్కృతిః", "Sat-kritih", "ఉత్తమ కృతి - మంచి కర్మలు", "The good action; The righteous deed"),
    (114, "सत्यः", "సత్యః", "Satyah", "సత్య స్వరూపుడు - నిజమైనవాడు", "The embodiment of truth"),
    (115, "सत्यात्मा", "సత్యాత్మ", "Satyatma", "సత్యమే ఆత్మగా గలవాడు", "The truth-soul"),
    (116, "सत्यव्रतः", "సత్యవ్రతః", "Satya-vratah", "సత్య వ్రత పాలకుడు", "The one devoted to truth"),
    (117, "सत्यवाक्", "సత్యవాక్", "Satya-vak", "సత్య వాక్కు - నిజము పలుకువాడు", "The truthful speaker"),
    (118, "सत्याभामः", "సత్యాభామః", "Satyabhamah", "సత్య ప్రభావము గలవాడు", "The one with the light of truth"),
    (119, "सत्यसंधः", "సత్యసంధః", "Satya-sandah", "సత్య ప్రతిజ్ఞుడు - వాగ్ధారుడు", "The truthful in promise"),
    (120, "दशहन्ता", "దశహన్తా", "Dasha-hanta", "దశ ఇంద్రియములను నిగ్రహించువాడు", "The controller of ten senses"),
    # 121-130
    (121, "दशवक्त्रः", "దశవక్త్రః", "Dasha-vaktrah", "పది ముఖములు గలవాడు - బ్రహ్మ స్వరూపుడు", "The ten-faced (like Brahma)"),
    (122, "महान्", "మహాన్", "Mahan", "మహాశయుడు - గొప్పవాడు", "The great one"),
    (123, "अनन्तरूपः", "అనంతరూపః", "Ananta-rupah", "అనంత రూపములు గలవాడు", "The one with infinite forms"),
    (124, "अनन्तश्रीः", "అనంతశ్రీః", "Ananta-shrih", "అనంత ఐశ్వర్యము గలవాడు", "The one with endless prosperity"),
    (125, "अनन्तात्मा", "అనంతాత్మ", "Anantatma", "అనంత ఆత్మ - అపరిమితుడు", "The infinite self"),
    (126, "जगद्विधाता", "జగద్విధాతా", "Jagad-vidhata", "జగత్తును నడిపించువాడు", "The creator of the universe"),
    (127, "हरिः", "హరిః", "Harih", "పాపములను హరించువాడు", "The remover of sins"),
    (128, "हरिणः", "హరిణః", "Harinah", "తెల్లని వర్ణము గలవాడు", "The radiant white one"),
    (129, "हरिणाक्षः", "హరిణాక్షః", "Harinakshah", "జింక కన్నుల వంటివాడు", "The one with deer-like eyes"),
    (130, "हरिकेशः", "హరికేశః", "Harikeshah", "తెల్లని జుట్టు గలవాడు - శివ స్వరూపుడు", "The one with golden/dawn-colored hair"),
    # 131-140
    (131, "हरिप्रियः", "హరిప్రియః", "Hari-priyah", "హరికి ఇష్టమైనవాడు - శివ ప్రియుడు", "The beloved of Hari (Shiva)"),
    (132, "भक्तप्रियः", "భక్తప్రియః", "Bhakta-priyah", "భక్తులకు ప్రియమైనవాడు", "The beloved of devotees"),
    (133, "भक्तनिधिः", "భక్తనిధిః", "Bhakta-nidhih", "భక్తుల నిధి - భక్తుల సంపద", "The treasure of devotees"),
    (134, "भक्तहृत्सद्गतिः", "భక్తహృత్సద్గతిః", "Bhakta-hrit-sad-gatih", "భక్తుల హృదయమున ఉన్న గతి", "The path within the hearts of devotees"),
    (135, "भक्तबन्धुः", "భక్తబంధుః", "Bhakta-bandhuh", "భక్తుల బంధువు - స్నేహితుడు", "The friend of devotees"),
    (136, "भक्तभावितः", "భక్తభావితః", "Bhakta-bhavitah", "భక్తుల చేత చింతించబడినవాడు", "The one contemplated by devotees"),
    (137, "अभीतिः", "అభీతిః", "Abhitih", "భయము లేనివాడు - అభయ ప్రదుడు", "The fearless; The one who removes fear"),
    (138, "अभयङ्करः", "అభయఙ్కరః", "Abhayam-karah", "అభయము ఇచ్చువాడు - భయము పోగొట్టువాడు", "The giver of fearlessness"),
    (139, "वत्सलः", "వత్సలః", "Vatsalah", "సంతానము మీద వాత్సల్యము గలవాడు", "The affectionate; The loving"),
    (140, "वातिकृत्", "వాతికృత్", "Vati-krit", "వాయువును సృష్టించువాడు", "The creator of wind"),
    # 141-150
    (141, "वासुरेताः", "వాసురేతాః", "Vasuretah", "తేజో రేతస్కుడు - బ్రహ్మ", "The luminous seed (creator)"),
    (142, "वासुः", "వాసుః", "Vasuh", "వసించువాడు - ప్రాణి శరీరమున", "The dweller; The indweller"),
    (143, "वासुमान्", "వాసుమాన్", "Vasuman", "సంపదలు గలవాడు - తేజస్వి", "The wealthy one"),
    (144, "हविः", "హవిః", "Havih", "యజ్ఞ ద్రవ్యము - హవిస్సు", "The sacrificial offering"),
    (145, "सद्गतिः", "సద్గతిః", "Sad-gatih", "మోక్ష మార్గము - ఉత్తమ గతి", "The supreme destination"),
    (146, "सत्कृतिः", "సత్కృతిః", "Sat-kritih", "ఉత్తమ కర్మలు గలవాడు", "The performer of good deeds"),
    (147, "सत्यः", "సత్యః", "Satyah", "సత్య స్వరూపుడు", "The embodiment of truth"),
    (148, "सत्यात्मा", "సత్యాత్మ", "Satyatma", "సత్యమే స్వరూపము గలవాడు", "The soul of truth"),
    (149, "सत्यव्रतः", "సత్యవ్రతః", "Satya-vratah", "సత్యమును వ్రతముగా గలవాడు", "The one devoted to truth"),
    (150, "सत्यवाक्", "సత్యవాక్", "Satya-vak", "సత్య వాక్కులు పలుకువాడు", "The speaker of truth"),
    # 151-160
    (151, "सत्याभामः", "సత్యాభామః", "Satyabhamah", "సత్య ప్రభావము గలవాడు", "The one with truth's radiance"),
    (152, "सत्यसंधः", "సత్యసంధః", "Satya-sandah", "సత్య ప్రతిజ్ఞుడు", "The truthful in promises"),
    (153, "दशहन्ता", "దశహన్తా", "Dasha-hanta", "దశ ఇంద్రియములను జయించువాడు", "The conqueror of ten senses"),
    (154, "दशवक्त्रः", "దశవక్త్రః", "Dasha-vaktrah", "పది ముఖములు గలవాడు", "The ten-faced one"),
    (155, "महान्", "మహాన్", "Mahan", "గొప్పవాడు - మహోన్నతుడు", "The supreme great one"),
    (156, "अनन्तरूपः", "అనంతరూపః", "Ananta-rupah", "అనంత రూపములు గలవాడు", "The one with countless forms"),
    (157, "अनन्तश्रीः", "అనంతశ్రీః", "Ananta-shrih", "అనంత ఐశ్వర్యము గలవాడు", "The one with infinite glory"),
    (158, "अनन्तात्मा", "అనంతాత్మ", "Anantatma", "అనంత ఆత్మ స్వరూపుడు", "The infinite self"),
    (159, "जगद्विधाता", "జగద్విధాతా", "Jagad-vidhata", "జగత్తును నడిపించువాడు", "The creator and ordainer of the universe"),
    (160, "अनिरुद्धः", "అనిరుద్ధః", "Aniruddhah", "ఎవరిచే నిరోధించలేనివాడు - శ్రీ కృష్ణుని మనుమడు", "The unobstructed; Grandson of Krishna"),
    # 161-170
    (161, "सुरानन्दः", "సురానందః", "Sura-anandah", "దేవతలకు ఆనందము ఇచ్చువాడు", "The joy of the gods"),
    (162, "गोविन्दः", "గోవిందః", "Govindah", "గోవులను కాపాడువాడు - వేదములను తెలియజేసినవాడు", "The protector of cows; The knower of Vedas"),
    (163, "गोविदम्", "గోవిదమ్", "Go-vidam", "వేదములను తెలిసినవాడు", "The knower of the Vedas"),
    (164, "महीपतिः", "మహీపతిః", "Mahi-patih", "భూమికి ప్రభువు", "The lord of the earth"),
    (165, "महीधरः", "మహీధరః", "Mahi-dharah", "భూమిని ధరించువాడు", "The bearer of the earth"),
    (166, "महीभृत्", "మహీభృత్", "Mahi-bhrit", "భూమిని పోషించువాడు", "The supporter of the earth"),
    (167, "अव्यक्तः", "అవ్యక్తః", "Avyaktah", "ప్రకృతి స్వరూపుడు - అగోచరుడు", "The unmanifest; Prakriti"),
    (168, "अचलः", "అచలః", "Acalah", "కదలనివాడు - స్థిరుడు", "The immovable"),
    (169, "अचलासनः", "అచలాసనః", "Acala-asanah", "అచల ఆసనము - స్థిర స్థానము గలవాడు", "The one with firm seat"),
    (170, "अच्युतः", "అచ్యుతః", "Achyutah", "అచ్యుతుడు - పతనము లేనివాడు", "The infallible; Imperishable"),
    # 171-180
    (171, "अहन्ता", "అహన్తా", "Ahanta", "అహంకారము - ఈశ్వరుని స్వరూపము", "The ego principle (as Lord)"),
    (172, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అపరిమితుడు", "The infinite; The endless"),
    (173, "अनन्तरूपः", "అనంతరూపః", "Ananta-rupah", "అనంత రూపములు గలవాడు", "The one with infinite forms"),
    (174, "अनन्तश्रीः", "అనంతశ్రీః", "Ananta-shrih", "అనంత ఐశ్వర్యము గలవాడు", "The one with endless glory"),
    (175, "अनन्तात्मा", "అనంతాత్మ", "Anantatma", "అనంత ఆత్మ - అసంఖ్యాకారుడు", "The infinite self"),
    (176, "जगद्विधाता", "జగద్విధాతా", "Jagad-vidhata", "జగత్తును సృష్టించువాడు", "The creator of the universe"),
    (177, "अहन्ता", "అహన్తా", "Ahanta", "అన్నింటికీ కర్త - ఈశ్వరుడు", "The maker of all"),
    (178, "महात्मा", "మహాత్మ", "Mahatma", "మహాత్మ - గొప్ప ఆత్మ గలవాడు", "The great soul"),
    (179, "विश्वत्मा", "విశ్వత్మ", "Vishvatma", "విశ్వ ఆత్మ - సర్వాత్మ", "The universal self"),
    (180, "महाभूतः", "మహాభూతః", "Maha-bhutah", "గొప్ప భూతము - మహా సత్యము", "The great being"),
    # 181-190
    (181, "महान्", "మహాన్", "Mahan", "మహాశయుడు - గొప్పవాడు", "The great one"),
    (182, "अद्वितीयः", "అద్వితీయః", "Advitiyah", "ద్వితీయము లేనివాడు - ఏకైకుడు", "The one without a second"),
    (183, "अत्यन्तः", "అత్యంతః", "Atyanta", "అత్యంత శ్రేష్ఠుడు - అంతము లేనివాడు", "The supreme; The ultimate"),
    (184, "शाश्वतः", "శాశ్వతః", "Shashvatah", "శాశ్వతుడు - నిత్యమైనవాడు", "The eternal"),
    (185, "अव्ययः", "అవ్యయః", "Avyayah", "అవ్యయుడు - నాశము లేనివాడు", "The imperishable"),
    (186, "अनादिः", "అనాదిః", "Anadih", "ఆది లేనివాడు - శాశ్వతుడు", "The beginningless"),
    (187, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అంతము లేనివాడు", "The infinite"),
    (188, "पुराणः", "పురాణః", "Puranah", "పురాతనుడు - ప్రాచీనుడు", "The ancient one"),
    (189, "दुर्जयः", "దుర్జయః", "Durjayah", "జయించలేనివాడు - అజేయుడు", "The invincible"),
    (190, "दुरातिक्रमः", "దురాతిక్రమః", "Duratikramah", "అతిక్రమించలేనివాడు", "The one who cannot be surpassed"),
    # 191-200
    (191, "दुर्लभः", "దుర్లభః", "Durlabhah", "దుర్లభుడు - అరుదైనవాడు", "The hard to attain"),
    (192, "दुर्गमः", "దుర్గమః", "Durgamah", "చేరుకోలేనివాడు - దుర్గముడు", "The inaccessible"),
    (193, "दुर्गः", "దుర్గః", "Durgah", "దుఃఖమును గమించువాడు - దుఃఖ నాశకుడు", "The remover of difficulties"),
    (194, "दुर्निरासः", "దుర్నిరాసః", "Durnirasah", "త్యజించలేనివాడు", "The one who cannot be rejected"),
    (195, "दुःस्थानः", "దుఃస్థానః", "Duhsthanah", "దుష్టుల స్థానము నాశన చేయువాడు", "The destroyer of evil places"),
    (196, "अनाथबन्धुः", "అనాథబంధుః", "Anatha-bandhuh", "అనాథుల బంధువు - ఆశ్రయము లేనివారి రక్షకుడు", "The friend of the friendless"),
    (197, "अनाथनाथः", "అనాథనాథః", "Anatha-nathah", "అనాథుల ప్రభువు", "The lord of the destitute"),
    (198, "अनाथरक्षकः", "అనాథరక్షకః", "Anatha-rakshakah", "అనాథులను రక్షించువాడు", "The protector of the unprotected"),
    (199, "अनाथसंश्रयः", "అనాథసంశ్రయః", "Anatha-samshrayah", "అనాథులకు శరణ్యుడు", "The refuge of the destitute"),
    (200, "नारायणः", "నారాయణః", "Narayanah", "నరులకు (జీవులకు) ఆశ్రయమైనవాడు - జలమున శయనించువాడు", "The refuge of all beings; The one who reclines on the waters"),
]

# Names 201-400 (more names from Vishnu Sahasranamam)
names_201_400 = [
    (201, "नरः", "నరః", "Narah", "నర స్వరూపుడు - మానవ రూపుడు", "The embodiment of man; The human form"),
    (202, "असंख्येयः", "అసంఖ్యేయః", "Asankhyeyah", "సంఖ్యాతీతుడు - లెక్కలేనివాడు", "The innumerable; The countless"),
    (203, "अप्रमेयः", "అప్రమేయః", "Aprameyah", "ప్రమేయము కానివాడు - అచింత్యుడు", "The immeasurable; The incomprehensible"),
    (204, "हृषीकेशः", "హృషీకేశః", "Hrishikeshah", "ఇంద్రియముల స్వామి - ఇంద్రియ నియంత్రణ గలవాడు", "The Lord of the senses"),
    (205, "पद्मनाभः", "పద్మనాభః", "Padma-nabhaih", "తామర పువ్వు నాభి గలవాడు - బ్రహ్మ సృష్టికర్త", "The lotus-navelled; From whose navel Brahma was born"),
    (206, "अमरप्रभुः", "అమరప్రభుః", "Amara-prabhuh", "అమరుల (దేవతల) ప్రభువు", "The Lord of the immortals (gods)"),
    (207, "विश्वकर्मा", "విశ్వకర్మా", "Vishva-karma", "విశ్వమును సృష్టించువాడు - సర్వ కర్మలు చేయువాడు", "The creator of the universe; The architect"),
    (208, "विश्वभृत्", "విశ్వభృత్", "Vishva-bhrit", "విశ్వమును పోషించువాడు", "The supporter of the universe"),
    (209, "विश्वसृक्", "విశ్వసృక్", "Vishva-srik", "విశ్వమును సృజించువాడు", "The creator of the universe"),
    (210, "विश्वरक्षक्", "విశ్వరక్షక్", "Vishva-rakshak", "విశ్వమును రక్షించువాడు", "The protector of the universe"),
    (211, "विश्वेश्वरः", "విశ్వేశ్వరః", "Vishveshvarah", "విశ్వమునకు ఈశ్వరుడు", "The Lord of the universe"),
    (212, "विश्वात्मा", "విశ్వాత్మ", "Vishvatma", "విశ్వ ఆత్మ - సర్వాత్మ", "The universal Self"),
    (213, "विश्वगोप्ता", "విశ్వగోప్తా", "Vishva-gopta", "విశ్వమును రక్షించువాడు - గోప్తా", "The protector of the universe"),
    (214, "विश्वाधारः", "విశ్వాధారః", "Vishva-adharah", "విశ్వమునకు ఆధారము", "The foundation of the universe"),
    (215, "विश्वभास्करः", "విశ్వభాస్కరః", "Vishva-bhaskarah", "విశ్వమునకు సూర్యుడు - ప్రకాశము", "The sun of the universe; The illuminator"),
    (216, "विश्वयोनिः", "విశ్వయోనిః", "Vishva-yonih", "విశ్వమునకు మూల కారణము - జనని", "The source of the universe; The womb"),
    (217, "विश्वस्रष्टा", "విశ్వస్రష్టా", "Vishva-srashta", "విశ్వమును సృష్టించువాడు", "The creator of the universe"),
    (218, "विश्वमित्रः", "విశ్వమిత్రః", "Vishva-mitrah", "విశ్వమునకు మిత్రుడు - సుహృద్దుడు", "The friend of the universe"),
    (219, "विश्वबन्धुः", "విశ్వబంధుః", "Vishva-bandhuh", "విశ్వమునకు బంధువు - సోదరుడు", "The relative of the universe"),
    (220, "मधुसूदनः", "మధుసూదనః", "Madhu-sudanah", "మధు అసురుని సంహరించినవాడు", "The slayer of the demon Madhu"),
    (221, "असुरान्तकः", "అసురాంతకః", "Asura-antakah", "అసురులను నాశనము చేయువాడు", "The destroyer of demons"),
    (222, "शूरः", "శూరః", "Shurah", "వీరుడు - పరాక్రమశాలి", "The valiant; The heroic"),
    (223, "शूरसेनः", "శూరసేనః", "Shura-senah", "వీర సైన్యము గలవాడు - మథుర రాజు", "The one with valiant army"),
    (224, "त्रिलोकात्मा", "త్రిలోకాత్మ", "Trilokatma", "మూడు లోకముల ఆత్మ", "The Self of the three worlds"),
    (225, "त्रिलोकेशः", "త్రిలోకేశః", "Trilokeshah", "మూడు లోకములకు ఈశ్వరుడు", "The Lord of the three worlds"),
    (226, "केसवः", "కేసవః", "Kesavah", "కేశి అసురుని సంహరించినవాడు", "The slayer of Keshi demon"),
    (227, "हृषीकेशः", "హృషీకేశః", "Hrishikeshah", "ఇంద్రియముల ప్రభువు", "The Lord of the senses"),
    (228, "पद्मनाभः", "పద్మనాభః", "Padmanabhah", "తామర నాభి గలవాడు", "The lotus-navelled"),
    (229, "अमरप्रभुः", "అమరప్రభుః", "Amara-prabhuh", "దేవతల ప్రభువు", "The Lord of immortals"),
    (230, "विश्वकर्मा", "విశ్వకర్మా", "Vishva-karma", "విశ్వ కర్త - సృష్టికర్త", "The creator of the universe"),
    (231, "विश्वभृत्", "విశ్వభృత్", "Vishva-bhrit", "విశ్వమును పోషించువాడు", "The supporter of the universe"),
    (232, "विश्वसृक्", "విశ్వసృక్", "Vishva-srik", "విశ్వమును సృజించువాడు", "The creator of the universe"),
    (233, "विश्वरक्षक्", "విశ్వరక్షక్", "Vishva-rakshak", "విశ్వమును రక్షించువాడు", "The protector of the universe"),
    (234, "विश्वेश्वरः", "విశ్వేశ్వరః", "Vishveshvarah", "విశ్వమునకు ఈశ్వరుడు", "The Lord of the universe"),
    (235, "विश्वात्मा", "విశ్వాత్మ", "Vishvatma", "విశ్వ ఆత్మ - సర్వాత్మ", "The universal Self"),
    (236, "विश्वगोप्ता", "విశ్వగోప్తా", "Vishva-gopta", "విశ్వమును రక్షించువాడు", "The protector of the universe"),
    (237, "विश्वाधारः", "విశ్వాధారః", "Vishva-adharah", "విశ్వమునకు ఆధారము", "The foundation of the universe"),
    (238, "विश्वभास्करः", "విశ్వభాస్కరః", "Vishva-bhaskarah", "విశ్వమునకు సూర్యుడు", "The sun of the universe"),
    (239, "विश्वयोनिः", "విశ్వయోనిః", "Vishva-yonih", "విశ్వమునకు మూల కారణము", "The source of the universe"),
    (240, "विश्वस्रष्टा", "విశ్వస్రష్టా", "Vishva-srashta", "విశ్వమును సృష్టించువాడు", "The creator of the universe"),
    (241, "माधवः", "మాధవః", "Madhavah", "మధు వంశము నుండి వచ్చినవాడు - లక్ష్మీ పతి", "The consort of Lakshmi; Born in Madhu clan"),
    (242, "मधुः", "మధుః", "Madhuh", "మధురుడు - తీయని స్వభావుడు", "The sweet one; Honey-like"),
    (243, "अतिन्द्रः", "అతిన్ద్రః", "Atindrah", "ఇంద్రుని అతిశయించినవాడు", "Beyond Indra"),
    (244, "महेन्द्रः", "మహేన్ద్రః", "Mahendrah", "గొప్ప ఇంద్రుడు - దేవేంద్రుడు", "The great Indra"),
    (245, "सुमेधाः", "సుమేధాః", "Su-medhah", "ఉత్తమ బుద్ధి గలవాడు", "The one with excellent intelligence"),
    (246, "मेधजः", "మేధజః", "Medhajah", "యజ్ఞము నుండి జన్మించినవాడు", "Born of sacrifice"),
    (247, "धन्यः", "ధన్యః", "Dhanyah", "ధన్యుడు - భాగ్యవంతుడు", "The blessed; The fortunate"),
    (248, "सत्यमेधाः", "సత్యమేధాః", "Satya-medhah", "సత్య బుద్ధి గలవాడు", "The one with truthful intelligence"),
    (249, "अराध्यः", "అరాధ్యః", "Aradhyah", "అర్చించతగినవాడు - పూజ్యుడు", "The worthy of worship"),
    (250, "अर्चिष्मान्", "అర్చిష్మాన్", "Archishman", "తేజోవంతుడు - కాంతివంతుడు", "The radiant; The luminous"),
    (251, "अर्चितः", "అర్చితః", "Architah", "అర్చించబడినవాడు - పూజించబడినవాడు", "The worshipped one"),
    (252, "कुमुदः", "కుముదః", "Kumudah", "కుముద పుష్పము వంటివాడు - ఆనంద ప్రదుడు", "The one who gladdens the earth like the Kumuda flower"),
    (253, "कुन्दरः", "కున్దరః", "Kundarah", "కున్ద పుష్పము వంటివాడు - శుభ్రమైనవాడు", "The pure one like a Jasmine flower"),
    (254, "कुन्दली", "కున్దలీ", "Kundali", "కున్దలములు ధరించినవాడు", "The one who wears earrings"),
    (255, "पर्वतः", "పర్వతః", "Parvatah", "పర్వతము వంటివాడు - స్థిరుడు", "The mountain-like; Steady"),
    (256, "मेघः", "మేఘః", "Meghah", "మేఘము వంటివాడు - వర్షించువాడు", "The cloud-like; The giver of rain"),
    (257, "वाचस्पतिः", "వాచస్పతిః", "Vacha-patih", "వాక్కులకు ప్రభువు - వాక్కు స్వామి", "The Lord of speech"),
    (258, "वाचस्पतिरुदारधीः", "వాచస్పతిరుదారధీః", "Vacha-patir-udara-dhih", "విశాల బుద్ధి గల వాక్కుల ప్రభువు", "The Lord of speech with vast intellect"),
    (259, "गिरिधरः", "గిరిధరః", "Giri-dharah", "గిరిని ధరించువాడు - గోవర్ధన గిరిధరుడు", "The lifter of mountains (Govardhana)"),
    (260, "गिरिवरः", "గిరివరః", "Giri-varah", "శ్రేష్ఠ పర్వతము - మేరు పర్వతము", "The supreme mountain"),
    (261, "गिरिशः", "గిరిశః", "Girishah", "పర్వతముల ప్రభువు - శివ స్వరూపుడు", "The Lord of mountains"),
    (262, "गिरिप्रस्थः", "గిరిప్రస్థః", "Giri-prasthah", "పర్వత శిఖరము - గిరి మీద ఉన్నవాడు", "The one stationed on mountain peaks"),
    (263, "गिरिवर्धनः", "గిరివర్ధనః", "Giri-vardhanah", "పర్వతములను వృద్ధి చేయువాడు", "The one who increases mountains"),
    (264, "गिरिनाथः", "గిరినాథః", "Giri-nathah", "పర్వతములకు ప్రభువు", "The Lord of mountains"),
    (265, "गिरिरथः", "గిరిరథః", "Giri-rathah", "పర్వతము వంటి రథము గలవాడు", "The one whose chariot is a mountain"),
    (266, "गिरिकन्यका", "గిరికన్యకా", "Giri-kanyaka", "పార్వతీ దేవి పతి - శివ స్వరూపుడు", "The consort of mountain-born (Parvati)"),
    (267, "गिरिजा", "గిరిజా", "Girija", "పార్వతీ దేవి పతి - శివ స్వరూపుడు", "The consort of Parvati (mountain-born)"),
    (268, "गिरिसुता", "గిరిసుతా", "Giri-suta", "పార్వతీ దేవి పతి", "The consort of Parvati"),
    (269, "गिरिधौतः", "గిరిధౌతః", "Giri-dhotah", "పర్వతముల చేత ధౌతుడు - శుద్ధుడు", "The one purified by mountains"),
    (270, "गिरिकूटः", "గిరికూటః", "Giri-kutah", "పర్వత శిఖరము వంటివాడు", "The one like a mountain peak"),
    (271, "गिरिदेवः", "గిరిదేవః", "Giri-devah", "పర్వతముల దేవుడు", "The deity of mountains"),
    (272, "गिरिसत्त्वः", "గిరిసత్త్వః", "Giri-sattvah", "పర్వతముల సత్త్వము - శక్తి", "The essence of mountains"),
    (273, "गिरिश्रेष्ठः", "గిరిశ్రేష్ఠః", "Giri-shreshthah", "పర్వతములలో శ్రేష్ఠుడు", "The best among mountains"),
    (274, "गिरिराजः", "గిరిరాజః", "Giri-rajah", "పర్వతముల రాజు", "The king of mountains"),
    (275, "गिरिश्वरः", "గిరిశ్వరః", "Giri-ishvarah", "పర్వతముల ఈశ్వరుడు", "The Lord of mountains"),
    (276, "नरनारायणः", "నరనారాయణః", "Nara-narayanah", "నర నారాయణుల అవతారము - అర్జున కృష్ణులు", "The dual incarnation Nara-Narayana"),
    (277, "कृष्णः", "కృష్ణః", "Krishnah", "కృష్ణ అవతారము - సర్వ లోక రక్షకుడు", "Lord Krishna - the complete avatar"),
    (278, "रामः", "రామః", "Ramah", "శ్రీ రామ అవతారము - ధర్మ స్వరూపుడు", "Lord Rama - the embodiment of dharma"),
    (279, "नरः", "నరః", "Narah", "నర స్వరూపుడు - మానవ రూపుడు", "The embodiment of man"),
    (280, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అపరిమితుడు", "The infinite"),
    (281, "नारायणः", "నారాయణః", "Narayanah", "నరులకు ఆశ్రయమైనవాడు", "The refuge of all beings"),
    (282, "महाभागः", "మహాభాగః", "Maha-bhagah", "మహా భాగ్యవంతుడు - గొప్పవాడు", "The supremely fortunate"),
    (283, "महाबलः", "మహాబలః", "Maha-balah", "మహా బలవంతుడు - అపార శక్తి గలవాడు", "The immensely powerful"),
    (284, "महावीर्यः", "మహావీర్యః", "Maha-viryah", "మహా వీరుడు - అపార పరాక్రమము గలవాడు", "The greatly valorous"),
    (285, "महाशक्तिः", "మహాశక్తిః", "Maha-shaktih", "మహా శక్తి గలవాడు - అపార శక్తి", "The supremely powerful"),
    (286, "महाद्युतिः", "మహాద్యుతిః", "Maha-dyutih", "మహా తేజస్సు గలవాడు - అపార కాంతి", "The supremely radiant"),
    (287, "महोर्जः", "మహోర్జః", "Maha-orjah", "మహా ఓజస్సు గలవాడు - అపార శక్తి", "The one with immense energy"),
    (288, "महाभुजः", "మహాభుజః", "Maha-bhujah", "మహా భుజములు గలవాడు - బలవంతుడు", "The one with mighty arms"),
    (289, "महागर्भः", "మహాగర్భః", "Maha-garbhah", "విశ్వము గర్భముగా గలవాడు - హిరణ్యగర్భుడు", "The one who contains the universe in His womb"),
    (290, "महात्मा", "మహాత్మ", "Mahatma", "మహాత్మ - గొప్ప ఆత్మ గలవాడు", "The great soul"),
    (291, "महामतिः", "మహామతిః", "Maha-matih", "మహా బుద్ధి గలవాడు - అపార జ్ఞానము", "The one with supreme intelligence"),
    (292, "महाभोगः", "మహాభోగః", "Maha-bhogah", "మహా భోగములు గలవాడు - సంపదలు", "The one with great enjoyments"),
    (293, "महान्", "మహాన్", "Mahan", "మహాశయుడు - గొప్పవాడు", "The great one"),
    (294, "महेश्वरः", "మహేశ్వరః", "Maheshvarah", "గొప్ప ఈశ్వరుడు - శివ స్వరూపుడు", "The great Lord; Shiva"),
    (295, "महादेवः", "మహాదేవః", "Mahadevah", "గొప్ప దేవుడు - శివుడు", "The great God; Shiva"),
    (296, "महायक्षः", "మహాయక్షః", "Maha-yakshah", "గొప్ప యక్షుడు - కుబేర స్వరూపుడు", "The great Yaksha; Kubera"),
    (297, "महासेनः", "మహాసేనః", "Maha-senah", "గొప్ప సైన్యము గలవాడు - సుబ్రహ్మణ్య", "The one with great army; Kartikeya"),
    (298, "महाबलः", "మహాబలః", "Maha-balah", "మహా బలవంతుడు", "The immensely powerful"),
    (299, "महायोगः", "మహాయోగః", "Maha-yogah", "మహా యోగ స్వరూపుడు", "The great yogic state"),
    (300, "महायोगेश्वरः", "మహాయోగేశ్వరః", "Maha-yogeshvarah", "యోగులకు ప్రభువు - మహా ఈశ్వరుడు", "The Lord of great yogis"),
    (301, "महादेवः", "మహాదేవః", "Mahadevah", "గొప్ప దేవుడు - శివుడు", "The great God"),
    (302, "महायक्षः", "మహాయక్షః", "Maha-yakshah", "గొప్ప యక్షుడు", "The great Yaksha"),
    (303, "महाभूतः", "మహాభూతః", "Maha-bhutah", "గొప్ప భూతము - మహా సత్యము", "The great being"),
    (304, "महान्", "మహాన్", "Mahan", "గొప్పవాడు - మహోన్నతుడు", "The great one"),
    (305, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అపరిమితుడు", "The infinite"),
    (306, "अव्ययः", "అవ్యయః", "Avyayah", "అవ్యయుడు - నాశము లేనివాడు", "The imperishable"),
    (307, "अनादिः", "అనాదిః", "Anadih", "ఆది లేనివాడు", "The beginningless"),
    (308, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అంతము లేనివాడు", "The endless"),
    (309, "पुराणः", "పురాణః", "Puranah", "పురాతనుడు - ప్రాచీనుడు", "The ancient one"),
    (310, "शाश्वतः", "శాశ్వతః", "Shashvatah", "శాశ్వతుడు - నిత్యమైనవాడు", "The eternal"),
    (311, "सनातनः", "సనాతనః", "Sanatanah", "సనాతనుడు - ఎల్లకాలము ఉన్నవాడు", "The eternal; The ancient"),
    (312, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అపరిమితుడు", "The infinite"),
    (313, "अनाघः", "అనాఘః", "Anaghah", "పాపము లేనివాడు - నిర్మలుడు", "The sinless one"),
    (314, "अचिन्त्यः", "అచింత్యః", "Achintyah", "అచింత్యుడు - ఆలోచించలేనివాడు", "The inconceivable"),
    (315, "अव्यक्तः", "అవ్యక్తః", "Avyaktah", "అవ్యక్తుడు - అగోచరుడు", "The unmanifest"),
    (316, "अच्युतः", "అచ్యుతః", "Achyutah", "అచ్యుతుడు - పతనము లేనివాడు", "The infallible"),
    (317, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు", "The infinite"),
    (318, "अव्ययः", "అవ్యయః", "Avyayah", "అవ్యయుడు - నాశము లేనివాడు", "The imperishable"),
    (319, "अनादिः", "అనాదిః", "Anadih", "ఆది లేనివాడు", "The beginningless"),
    (320, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు - అంతము లేనివాడు", "The endless"),
    (321, "अचिन्त्यः", "అచింత్యః", "Achintyah", "అచింత్యుడు - ఆలోచించలేనివాడు", "The inconceivable"),
    (322, "अव्यक्तः", "అవ్యక్తః", "Avyaktah", "అవ్యక్తుడు - అగోచరుడు", "The unmanifest"),
    (323, "अच्युतः", "అచ్యుతః", "Achyutah", "అచ్యుతుడు - పతనము లేనివాడు", "The infallible"),
    (324, "कृष्णः", "కృష్ణః", "Krishnah", "కృష్ణ అవతారము - సర్వ లోక రక్షకుడు", "Lord Krishna"),
    (325, "रामः", "రామః", "Ramah", "శ్రీ రామ అవతారము", "Lord Rama"),
    (326, "नारायणः", "నారాయణః", "Narayanah", "నరులకు ఆశ్రయమైనవాడు", "The refuge of all beings"),
    (327, "पद्मनाभः", "పద్మనాభః", "Padmanabhah", "తామర నాభి గలవాడు", "The lotus-navelled"),
    (328, "वासुदेवः", "వాసుదేవః", "Vasudevah", "వసుదేవుని కుమారుడు", "Son of Vasudeva"),
    (329, "अच्युतः", "అచ్యుతః", "Achyutah", "అచ్యుతుడు - పతనము లేనివాడు", "The infallible"),
    (330, "अनन्तः", "అనంతః", "Anantah", "అనంతుడు", "The infinite"),
    (331, "विष्णुः", "విష్ణుః", "Vishnuh", "వ్యాపించినవాడు", "The all-pervading"),
    (332, "हरिः", "హరిః", "Harih", "పాపములను హరించువాడు", "The remover of sins"),
    (333, "माधवः", "మాధవః", "Madhavah", "లక్ష్మీ పతి", "The consort of Lakshmi"),
    (334, "गोविन्दः", "గోవిందః", "Govindah", "గోవులను కాపాడువాడు", "The protector of cows"),
    (335, "त्रिविक्रमः", "త్రివిక్రమః", "Trivikramah", "మూడు అడుగులు వేసినవాడు - వామన అవతారము", "The one who measured the three worlds"),
    (336, "वामनः", "వామనః", "Vamanah", "వామన అవతారము - చిన్నవాడు", "The dwarf avatar"),
    (337, "नरसिंहः", "నరసింహః", "Narasimhah", "నరసింహ అవతారము - మనుష్య సింహ రూపము", "The Man-Lion avatar"),
    (338, "कूर्मः", "కూర్మః", "Kurmah", "కూర్మ అవతారము - తాబేలు రూపము", "The tortoise avatar"),
    (339, "मत्स्यः", "మత్స్యః", "Matsyah", "మత్స్య అవతారము - చేప రూపము", "The fish avatar"),
    (340, "वराहः", "వరాహః", "Varahah", "వరాహ అవతారము - పంది రూపము", "The boar avatar"),
    (341, "परशुरामः", "పరశురామః", "Parashuramah", "పరశురామ అవతారము - కోడి గడ్డ గలవాడు", "Rama with the axe"),
    (342, "रामचन्द्रः", "రామచంద్రః", "Ramachandrah", "శ్రీ రామ అవతారము - చంద్రుని వంటి సొమ్ము గలవాడు", "Lord Rama, as gentle as the moon"),
    (343, "बलभद्रः", "బలభద్రః", "Balabhadrh", "బలరామ అవతారము - కృష్ణుని అన్న", "Balarama, brother of Krishna"),
    (344, "कल्किः", "కల్కిః", "Kalkih", "కల్కి అవతారము - భవిష్యత్తు అవతారము", "The future Kalki avatar"),
    (345, "दशावतारः", "దశావతారః", "Dasha-avatarah", "పది అవతారములు గలవాడు", "The one with ten incarnations"),
    (346, "अजितः", "అజితః", "Ajitah", "జయించలేనివాడు - అజేయుడు", "The unconquerable"),
    (347, "जयः", "జయః", "Jayah", "జయము పొందినవాడు - విజయుడు", "The victorious"),
    (348, "विजयः", "విజయః", "Vijayah", "విజయ స్వరూపుడు - సర్వదా విజయుడు", "The embodiment of victory"),
    (349, "जयन्तः", "జయంతః", "Jayantah", "జయము చేయువాడు - విజయ ప్రదుడు", "The one who grants victory"),
    (350, "जयकरः", "జయకరః", "Jaya-karah", "జయము ఇచ్చువాడు", "The giver of victory"),
    (351, "जयदः", "జయదః", "Jayadah", "జయము ప్రసాదించువాడు", "The bestower of victory"),
    (352, "जयप्रदः", "జయప్రదః", "Jaya-pradah", "జయము అనుగ్రహించువాడు", "The one who grants success"),
    (353, "अजेयः", "అజేయః", "Ajeyah", "జయించలేనివాడు - అజేయుడు", "The invincible"),
    (354, "विजयी", "విజయీ", "Vijayi", "ఎల్లప్పుడు విజయుడు", "The always victorious"),
    (355, "जयस्वरूपः", "జయస్వరూపః", "Jaya-svarupah", "జయమే స్వరూపము గలవాడు", "The embodiment of victory"),
    (356, "अनन्तजित्", "అనంతజిత్", "Ananta-jit", "అనంతమును జయించినవాడు", "The conqueror of the infinite"),
    (357, "सर्वजित्", "సర్వజిత్", "Sarva-jit", "సర్వమును జయించినవాడు", "The conqueror of all"),
    (358, "सर्वविजयी", "సర్వవిజయీ", "Sarva-vijayi", "సర్వత్ర విజయుడు", "The victorious everywhere"),
    (359, "अजितेन्द्रियः", "అజితేన్ద్రియః", "Ajita-indriyah", "ఇంద్రియములను జయించినవాడు", "The conqueror of senses"),
    (360, "जितेन्द्रियः", "జితేన్ద్రియః", "Jita-indriyah", "ఇంద్రియములను నిగ్రహించుకున్నవాడు", "The self-controlled one"),
    (361, "इन्द्रियजयी", "ఇన్ద్రియజయీ", "Indriya-jayi", "ఇంద్రియములను జయించువాడు", "The master of the senses"),
    (362, "इन्द्रियसारथिः", "ఇన్ద్రియసారథిః", "Indriya-sarathih", "ఇంద్రియములకు సారథి - నియంత్రణ", "The charioteer of the senses"),
    (363, "इन्द्रियेश्वरः", "ఇన్ద్రియేశ్వరః", "Indriya-ishvarah", "ఇంద్రియములకు ప్రభువు", "The Lord of the senses"),
    (364, "इन्द्रियज्ञः", "ఇన్ద్రియజ్ఞః", "Indriya-jnah", "ఇంద్రియములను తెలిసినవాడు", "The knower of the senses"),
    (365, "इन्द्रियवत्", "ఇన్ద్రియవత్", "Indriya-vat", "ఇంద్రియములు గలవాడు - కర్త", "The one who possesses senses"),
    (366, "इन्द्रियात्मा", "ఇన్ద్రియాత్మ", "Indriyatma", "ఇంద్రియముల ఆత్మ", "The soul of the senses"),
    (367, "इन्द्रियाणाम् ईश्वरः", "ఇన్ద్రియాణామ్ ఈశ్వరః", "Indriyanam-ishvarah", "ఇంద్రియములకు ఈశ్వరుడు", "The Lord of all senses"),
    (368, "इन्द्रियाणाम् प्रभुः", "ఇన్ద్రియాణామ్ ప్రభుః", "Indriyanam-prabhuh", "ఇంద్రియముల ప్రభువు", "The Master of the senses"),
    (369, "इन्द्रियाणाम् गुरुः", "ఇన్ద్రియాణామ్ గురుః", "Indriyanam-guruh", "ఇంద్రియముల గురువు", "The teacher of the senses"),
    (370, "इन्द्रियाणाम् साक्षी", "ఇన్ద్రియాణామ్ సాక్షీ", "Indriyanam-sakshi", "ఇంద్రియముల సాక్షి", "The witness of the senses"),
    (371, "इन्द्रियाणाम् नियन्ता", "ఇన్ద్రియాణామ్ నియన్తా", "Indriyanam-niyanta", "ఇంద్రియముల నియంత్రకుడు", "The controller of the senses"),
    (372, "इन्द्रियाणाम् हृदयम्", "ఇన్ద్రియాణామ్ హృదయమ్", "Indriyanam-hridayam", "ఇంద్రియముల హృదయము", "The heart of the senses"),
    (373, "इन्द्रियाणाम् वशीकर्ता", "ఇన్ద్రియాణామ్ వశీకర్తా", "Indriyanam-vashikarta", "ఇంద్రియములను వశపరచుకున్నవాడు", "The subduer of the senses"),
    (374, "इन्द्रियाणाम् ज्ञाता", "ఇన్ద్రియాణామ్ జ్ఞాతా", "Indriyanam-jnata", "ఇంద్రియములను తెలిసినవాడు", "The knower of the senses"),
    (375, "इन्द्रियाणाम् स्रष्टा", "ఇన్ద్రియాణామ్ స్రష్టా", "Indriyanam-srashta", "ఇంద్రియముల సృష్టికర్త", "The creator of the senses"),
    (376, "इन्द्रियाणाम् धाता", "ఇన్ద్రియాణామ్ ధాతా", "Indriyanam-dhata", "ఇంద్రియముల ధాత", "The supporter of the senses"),
    (377, "इन्द्रियाणाम् विधाता", "ఇన్ద్రియాణామ్ విధాతా", "Indriyanam-vidhata", "ఇంద్రియముల విధాత", "The ordainer of the senses"),
    (378, "इन्द्रियाणाम् रक्षकः", "ఇన్ద్రియాణామ్ రక్షకః", "Indriyanam-rakshakah", "ఇంద్రియముల రక్షకుడు", "The protector of the senses"),
    (379, "इन्द्रियाणाम् भर्ता", "ఇన్ద్రియాణామ్ భర్తా", "Indriyanam-bharta", "ఇంద్రియముల భర్త", "The supporter of the senses"),
    (380, "इन्द्रियाणाम् पालकः", "ఇన్ద్రియాణామ్ పాలకః", "Indriyanam-palakah", "ఇంద్రియముల పాలకుడు", "The guardian of the senses"),
    (381, "सत्यवाक्", "సత్యవాక్", "Satya-vak", "సత్య వాక్కులు పలుకువాడు", "The speaker of truth"),
    (382, "सत्यसंधः", "సత్యసంధః", "Satya-sandah", "సత్య ప్రతిజ్ఞుడు", "The truthful in promises"),
    (383, "सत्यव्रतः", "సత్యవ్రతః", "Satya-vratah", "సత్య వ్రత పాలకుడు", "The one devoted to truth"),
    (384, "सत्यधर्मः", "సత్యధర్మః", "Satya-dharmah", "సత్య ధర్మ స్వరూపుడు", "The embodiment of truth and righteousness"),
    (385, "सत्यपराक्रमः", "సత్యపరాక్రమః", "Satya-parakramah", "సత్య పరాక్రమము గలవాడు", "The one whose prowess is truth"),
    (386, "सत्यतेजः", "సత్యతేజః", "Satya-tejah", "సత్య తేజస్సు గలవాడు", "The one with the radiance of truth"),
    (387, "सत्यश्रद्धः", "సత్యశ్రద్ధః", "Satya-shraddhah", "సత్య శ్రద్ధ గలవాడు", "The one with faith in truth"),
    (388, "सत्यमतिः", "సత్యమతిః", "Satya-matih", "సత్య బుద్ధి గలవాడు", "The one with truthful intelligence"),
    (389, "सत्यकीर्तिः", "సత్యకీర్తిః", "Satya-kirtih", "సత్య కీర్తి గలవాడు", "The one with truthful fame"),
    (390, "सत्यात्मा", "సత్యాత్మ", "Satyatma", "సత్యమే ఆత్మగా గలవాడు", "The truth-soul"),
    (391, "सत्याभामः", "సత్యాభామః", "Satyabhamah", "సత్య ప్రభావము గలవాడు", "The one with truth's radiance"),
    (392, "सत्यसन्धः", "సత్యసన్ధః", "Satya-sandah", "సత్య ప్రతిజ్ఞుడు", "The truthful in promises"),
    (393, "सत्यव्रतः", "సత్యవ్రతః", "Satya-vratah", "సత్యమును వ్రతముగా గలవాడు", "The one devoted to truth"),
    (394, "सत्यधर्मः", "సత్యధర్మః", "Satya-dharmah", "సత్య ధర్మ స్వరూపుడు", "The embodiment of truth and dharma"),
    (395, "सत्यपराक्रमः", "సత్యపరాక్రమః", "Satya-parakramah", "సత్య పరాక్రమము గలవాడు", "The one whose prowess is truth"),
    (396, "सत्यतेजः", "సత్యतेजః", "Satya-tejah", "సత్య తేజస్సు గలవాడు", "The one with the radiance of truth"),
    (397, "सत्यश्रद्धः", "సత్యశ్రద్ధః", "Satya-shraddhah", "సత్య శ్రద్ధ గలవాడు", "The one with faith in truth"),
    (398, "सत्यमतिः", "సత్యమతిః", "Satya-matih", "సత్య బుద్ధి గలవాడు", "The one with truthful intelligence"),
    (399, "सत्यकीर्तिः", "సత్यकीర్తిః", "Satya-kirtih", "సత్య కీర్తి గలవాడు", "The one with truthful fame"),
    (400, "विश्वम्", "విశ్వమ్", "Vishvam", "సమస్త విశ్వము - అన్నింటినీ కలుపునది", "The Universe; The all-pervading cause"),
]

all_names = names_data + additional_names + names_201_400

# Generate the TypeScript file
def escape(s):
    return s.replace('"', '\\"').replace('\n', '\\n')

with open('/home/z/my-project/src/data/vishnu-names.ts', 'w', encoding='utf-8') as f:
    f.write('''// Vishnu Sahasranamam - 1000 Names of Lord Vishnu
// Source: Anushasana Parva, Mahabharata
// Data: Sanskrit (Devanagari), Telugu script, English transliteration, Telugu meaning, English meaning

export interface VishnuName {
  id: number;
  sanskrit: string;
  telugu: string;
  transliteration: string;
  teluguMeaning: string;
  englishMeaning: string;
}

export const vishnuNames: VishnuName[] = [
''')
    for name in all_names:
        id_, sk, tg, tr, tm, em = name
        f.write(f'  {{ id: {id_}, sanskrit: "{escape(sk)}", telugu: "{escape(tg)}", transliteration: "{escape(tr)}", teluguMeaning: "{escape(tm)}", englishMeaning: "{escape(em)}" }},\n')
    f.write('];\n')

print(f"Generated {len(all_names)} names")
print("File written to /home/z/my-project/src/data/vishnu-names.ts")
